// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: gear-grpc.proto

package gear_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GearGrpcService_CallVoucherIssue_FullMethodName = "/gear_grpc.GearGrpcService/CallVoucherIssue"
)

// GearGrpcServiceClient is the client API for GearGrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GearGrpcServiceClient interface {
	CallVoucherIssue(ctx context.Context, in *VoucherParams, opts ...grpc.CallOption) (*EncodedVoucherIssue, error)
}

type gearGrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGearGrpcServiceClient(cc grpc.ClientConnInterface) GearGrpcServiceClient {
	return &gearGrpcServiceClient{cc}
}

func (c *gearGrpcServiceClient) CallVoucherIssue(ctx context.Context, in *VoucherParams, opts ...grpc.CallOption) (*EncodedVoucherIssue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncodedVoucherIssue)
	err := c.cc.Invoke(ctx, GearGrpcService_CallVoucherIssue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GearGrpcServiceServer is the server API for GearGrpcService service.
// All implementations must embed UnimplementedGearGrpcServiceServer
// for forward compatibility.
type GearGrpcServiceServer interface {
	CallVoucherIssue(context.Context, *VoucherParams) (*EncodedVoucherIssue, error)
	mustEmbedUnimplementedGearGrpcServiceServer()
}

// UnimplementedGearGrpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGearGrpcServiceServer struct{}

func (UnimplementedGearGrpcServiceServer) CallVoucherIssue(context.Context, *VoucherParams) (*EncodedVoucherIssue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallVoucherIssue not implemented")
}
func (UnimplementedGearGrpcServiceServer) mustEmbedUnimplementedGearGrpcServiceServer() {}
func (UnimplementedGearGrpcServiceServer) testEmbeddedByValue()                         {}

// UnsafeGearGrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GearGrpcServiceServer will
// result in compilation errors.
type UnsafeGearGrpcServiceServer interface {
	mustEmbedUnimplementedGearGrpcServiceServer()
}

func RegisterGearGrpcServiceServer(s grpc.ServiceRegistrar, srv GearGrpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedGearGrpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GearGrpcService_ServiceDesc, srv)
}

func _GearGrpcService_CallVoucherIssue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoucherParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GearGrpcServiceServer).CallVoucherIssue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GearGrpcService_CallVoucherIssue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GearGrpcServiceServer).CallVoucherIssue(ctx, req.(*VoucherParams))
	}
	return interceptor(ctx, in, info, handler)
}

// GearGrpcService_ServiceDesc is the grpc.ServiceDesc for GearGrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GearGrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gear_grpc.GearGrpcService",
	HandlerType: (*GearGrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallVoucherIssue",
			Handler:    _GearGrpcService_CallVoucherIssue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gear-grpc.proto",
}
