// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: gear-grpc.proto

package gear_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoucherParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spender       string                 `protobuf:"bytes,1,opt,name=spender,proto3" json:"spender,omitempty"`
	Balance       string                 `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	CodeUploading bool                   `protobuf:"varint,3,opt,name=code_uploading,json=codeUploading,proto3" json:"code_uploading,omitempty"`
	Duration      int32                  `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoucherParams) Reset() {
	*x = VoucherParams{}
	mi := &file_gear_grpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoucherParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoucherParams) ProtoMessage() {}

func (x *VoucherParams) ProtoReflect() protoreflect.Message {
	mi := &file_gear_grpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoucherParams.ProtoReflect.Descriptor instead.
func (*VoucherParams) Descriptor() ([]byte, []int) {
	return file_gear_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *VoucherParams) GetSpender() string {
	if x != nil {
		return x.Spender
	}
	return ""
}

func (x *VoucherParams) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *VoucherParams) GetCodeUploading() bool {
	if x != nil {
		return x.CodeUploading
	}
	return false
}

func (x *VoucherParams) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type EncodedVoucherIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncodedCall   string                 `protobuf:"bytes,1,opt,name=encoded_call,json=encodedCall,proto3" json:"encoded_call,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncodedVoucherIssue) Reset() {
	*x = EncodedVoucherIssue{}
	mi := &file_gear_grpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncodedVoucherIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncodedVoucherIssue) ProtoMessage() {}

func (x *EncodedVoucherIssue) ProtoReflect() protoreflect.Message {
	mi := &file_gear_grpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncodedVoucherIssue.ProtoReflect.Descriptor instead.
func (*EncodedVoucherIssue) Descriptor() ([]byte, []int) {
	return file_gear_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *EncodedVoucherIssue) GetEncodedCall() string {
	if x != nil {
		return x.EncodedCall
	}
	return ""
}

var File_gear_grpc_proto protoreflect.FileDescriptor

const file_gear_grpc_proto_rawDesc = "" +
	"\n" +
	"\x0fgear-grpc.proto\x12\tgear_grpc\"\x86\x01\n" +
	"\rVoucherParams\x12\x18\n" +
	"\aspender\x18\x01 \x01(\tR\aspender\x12\x18\n" +
	"\abalance\x18\x02 \x01(\tR\abalance\x12%\n" +
	"\x0ecode_uploading\x18\x03 \x01(\bR\rcodeUploading\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x05R\bduration\"8\n" +
	"\x13EncodedVoucherIssue\x12!\n" +
	"\fencoded_call\x18\x01 \x01(\tR\vencodedCall2_\n" +
	"\x0fGearGrpcService\x12L\n" +
	"\x10CallVoucherIssue\x12\x18.gear_grpc.VoucherParams\x1a\x1e.gear_grpc.EncodedVoucherIssueB\x15Z\x13protocols/gear-grpcb\x06proto3"

var (
	file_gear_grpc_proto_rawDescOnce sync.Once
	file_gear_grpc_proto_rawDescData []byte
)

func file_gear_grpc_proto_rawDescGZIP() []byte {
	file_gear_grpc_proto_rawDescOnce.Do(func() {
		file_gear_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gear_grpc_proto_rawDesc), len(file_gear_grpc_proto_rawDesc)))
	})
	return file_gear_grpc_proto_rawDescData
}

var file_gear_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gear_grpc_proto_goTypes = []any{
	(*VoucherParams)(nil),       // 0: gear_grpc.VoucherParams
	(*EncodedVoucherIssue)(nil), // 1: gear_grpc.EncodedVoucherIssue
}
var file_gear_grpc_proto_depIdxs = []int32{
	0, // 0: gear_grpc.GearGrpcService.CallVoucherIssue:input_type -> gear_grpc.VoucherParams
	1, // 1: gear_grpc.GearGrpcService.CallVoucherIssue:output_type -> gear_grpc.EncodedVoucherIssue
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gear_grpc_proto_init() }
func file_gear_grpc_proto_init() {
	if File_gear_grpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gear_grpc_proto_rawDesc), len(file_gear_grpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gear_grpc_proto_goTypes,
		DependencyIndexes: file_gear_grpc_proto_depIdxs,
		MessageInfos:      file_gear_grpc_proto_msgTypes,
	}.Build()
	File_gear_grpc_proto = out.File
	file_gear_grpc_proto_goTypes = nil
	file_gear_grpc_proto_depIdxs = nil
}
