name: run linter

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Run Go linter
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
          check-latest: true

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest